name = "backend"
compatibility_date = "2024-08-06"
node_compat = true
[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNWQ0NzhkN2MtNmViYS00OTVjLWExM2EtMDBmNDdhZjVhZDI3IiwidGVuYW50X2lkIjoiNDNlMTUwOGFkYjE0OTUyZjg4YTkwYzU1ZjA1N2MzYTA4N2ViZjg4YTYxNTQ1NGZjMTkxODY2ZGE0ZjIzMjkwNCIsImludGVybmFsX3NlY3JldCI6IjBiYjYyYzg3LTFjMjUtNDk3NS04NDcxLTM1NTkzYjFjZjhmMiJ9.CMBsyA0nTodmYQKCVYc1fjjiKTQrNDkgWXyC1B9AQ_E"
Jwt_Secret="124421"

# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"